from PIL import Image, ImageTk

# Resized_images return a list of PhotoImages that is used for the
# calculator buttons, each images are resized
def Resized_images():
    Image_length = 80
    Image_height = 80
    Number1 = Image.open('Images\\1.png')
    resized_image = Number1.resize((Image_length, Image_height))
    Number1 = ImageTk.PhotoImage(resized_image)
    Number2 = Image.open('Images\\2.png')
    resized_image = Number2.resize((Image_length, Image_height))
    Number2 = ImageTk.PhotoImage(resized_image)
    Number3 = Image.open('Images\\3.png')
    resized_image = Number3.resize((Image_length, Image_height))
    Number3 = ImageTk.PhotoImage(resized_image)
    Number4 = Image.open('Images\\4.png')
    resized_image = Number4.resize((Image_length, Image_height))
    Number4 = ImageTk.PhotoImage(resized_image)
    Number5 = Image.open('Images\\5.png')
    resized_image = Number5.resize((Image_length, Image_height))
    Number5 = ImageTk.PhotoImage(resized_image)
    Number6 = Image.open('Images\\6.png')
    resized_image = Number6.resize((Image_length, Image_height))
    Number6 = ImageTk.PhotoImage(resized_image)
    Number7 = Image.open('Images\\7.png')
    resized_image = Number7.resize((Image_length, Image_height))
    Number7 = ImageTk.PhotoImage(resized_image)
    Number8 = Image.open('Images\\8.png')
    resized_image = Number8.resize((Image_length, Image_height))
    Number8 = ImageTk.PhotoImage(resized_image)
    Number9 = Image.open('Images\\9.png')
    resized_image = Number9.resize((Image_length, Image_height))
    Number9 = ImageTk.PhotoImage(resized_image)
    Number0 = Image.open('Images\\0.png')
    resized_image = Number0.resize((Image_length, Image_height))
    Number0 = ImageTk.PhotoImage(resized_image)
    Number00 = Image.open('Images\\00.png')
    resized_image = Number00.resize((Image_length, Image_height))
    Number00 = ImageTk.PhotoImage(resized_image)
    clear_img = Image.open('Images\\clear.png')
    resized_image = clear_img.resize((Image_length, Image_height))
    clear_img = ImageTk.PhotoImage(resized_image)
    difference_img = Image.open('Images\\difference.png')
    resized_image = difference_img.resize((Image_length, Image_height))
    difference_img = ImageTk.PhotoImage(resized_image)
    dot_img = Image.open('Images\\dot.png')
    resized_image = dot_img.resize((Image_length, Image_height))
    dot_img = ImageTk.PhotoImage(resized_image)
    equal_img = Image.open('Images\\equal.png')
    resized_image = equal_img.resize((Image_length, Image_height))
    equal_img = ImageTk.PhotoImage(resized_image)
    percent_img = Image.open('Images\\percent.png')
    resized_image = percent_img.resize((Image_length, Image_height))
    percent_img = ImageTk.PhotoImage(resized_image)
    product_img = Image.open('Images\\product.png')
    resized_image = product_img.resize((Image_length, Image_height))
    product_img = ImageTk.PhotoImage(resized_image)
    quotient_img = Image.open('Images\\quotient.png')
    resized_image = quotient_img.resize((Image_length, Image_height))
    quotient_img = ImageTk.PhotoImage(resized_image)
    remove_img = Image.open('Images\\remove.png')
    resized_image = remove_img.resize((Image_length, Image_height))
    remove_img = ImageTk.PhotoImage(resized_image)
    sum_img = Image.open('Images\\sum.png')
    resized_image = sum_img.resize((Image_length, Image_height))
    sum_img = ImageTk.PhotoImage(resized_image)
    return [Number0, Number00, Number1, Number2, Number3,
            Number4, Number5, Number6, Number7, Number8,
            Number9, clear_img, difference_img, dot_img, equal_img,
            percent_img, product_img, quotient_img, remove_img, sum_img]
